Add README.md
svelte-jp/quiz pull request #2
Opened 2021-05-20 05:12 UTC by myLifeAsaDog

とりあえずクイズの運用フローの叩き台をつくりました

2021-05-20 07:59 UTC, knj4484 requested changes
ありがとうございます。

内容と細かい文言の修正いくつかと質問がありますのでご確認お願いします。

2021-05-20 07:59 UTC, knj4484 commented on README.md
> +- ISSUEのフォーマットは下記を参考にしてください
```suggestion
- Issueのフォーマットは下記を参考にしてください
```

2021-05-20 07:59 UTC, knj4484 commented on README.md
> +  - 管理者に関しても募集中です！Svelte日本Discordの `#Svelteクイズ` にてご連絡ください
```suggestion
  - 管理者も募集中です！Svelte日本Discordの`#svelteクイズ`にてご連絡ください
```

応募する側の立場になって考えてみると、`#svelteクイズ`で連絡するのは心理的なハードルが高い気がするんですが、DMとかではだめですかね？

2021-05-20 07:59 UTC, knj4484 commented on README.md
> +### 01. 任意の投稿日のクイズのISSUEを立ててもらう
```suggestion
### 01. クイズのIssueを立ててもらう
```

2021-05-20 07:59 UTC, knj4484 commented on README.md
> +### 02. 管理者が精査を行い、ISSUE に可否のコメントする
```suggestion
### 02. 管理者が精査を行い、Issueに可否のコメントする
```

2021-05-20 07:59 UTC, knj4484 commented on README.md
> +- タイトルには投稿予定の日付を含むようにしてください
```suggestion
- タイトルには出題予定の日付を含むようにしてください（特に理由がなければIssueが作成されていない日を前の方から選んで下さい）
```

2021-05-20 07:59 UTC, knj4484 commented on README.md
> +  - クイズは現状では毎週、月水金の午前中に投稿しています
```suggestion
  - クイズは現状では毎週月水金の9時頃に出題、19時頃に解答・解説の発表をしています
```

2021-05-20 07:59 UTC, knj4484 commented on README.md
> +Svelte日本Discord で定期的に投稿している Svelteクイズ に投稿する問題を募集・管理するためのリポジトリです。
```suggestion
Svelte日本Discordで定期的に投稿しているSvelteクイズに投稿する問題を募集・管理するためのリポジトリです。
```

2021-05-20 07:59 UTC, knj4484 commented on README.md
> +- テーマは各自で判断してもらって構いませんが、SvelteのAPIのページの見出しと一致していることが望ましいです
「SvelteのAPIのページの見出しと一致していることが望ましい」はどういう意図でしょうか？

2021-05-20 07:59 UTC, knj4484 commented on README.md
> +- 何らかの理由により当日投稿できない、もしくは出題者本人による投稿を望まない場合は、ISSUE にてお知らせください
```suggestion
- 何らかの理由により当日投稿できない、もしくは問題作成者本人による投稿を望まない場合は、Issueにてお知らせください
```

2021-05-20 08:28 UTC, myLifeAsaDog commented on README.md
> +  - 管理者に関しても募集中です！Svelte日本Discordの `#Svelteクイズ` にてご連絡ください
個人的にはDMの方がハードル高いと思ってますけど、特に禁止する理由もないので両方受け入れる（DM でも #Svelteクイズ でもOK）にするのはどうでしょうか？

2021-05-20 08:34 UTC, myLifeAsaDog commented on README.md
> +- テーマは各自で判断してもらって構いませんが、SvelteのAPIのページの見出しと一致していることが望ましいです
https://gyazo.com/693243031b4e01cb2fcc42161534168c

これのことです、例えば「要素のアニメーション」とかではなく「Transition(ディレクティブ)」などにして欲しいということです。

2021-05-20 09:27 UTC, knj4484 commented on README.md
> +- テーマは各自で判断してもらって構いませんが、SvelteのAPIのページの見出しと一致していることが望ましいです
なるほど。Issueの読み手に対するドキュメント上での出題範囲（参照するドキュメントの範囲）の曖昧さを減らしたいということですね。

だとすると

- 複数の見出しに関わる出題も結構ありそう
- 日本語ドキュメントの現状の精度と精度向上の順番の観点からして、どちらかというとチュートリアルを参照してもらいたい

ということを踏まえて、ここは
```suggestion
- テーマは各自で選んでもらって構いませんが、[日本語ドキュメント](https://sveltejp.dev/)で解説されている内容にしてください
```
にしておいて、Issueテンプレートのテーマの部分に「Svelte日本語ドキュメントのチュートリアル/APIのページの見出しの中で出題内容に関するものを列挙する」旨を追記するっていうのでどうでしょう？

2021-05-20 09:27 UTC, knj4484 commented on README.md
> +  - 管理者に関しても募集中です！Svelte日本Discordの `#Svelteクイズ` にてご連絡ください
人によってコミュニケーションの感覚は違いますね。
両方受け受け入れることにしましょう。

2021-05-25 07:57 UTC, knj4484 commented on README.md
> +  - 管理者に関しても募集中です！Svelte日本Discordの `#Svelteクイズ` にてご連絡ください
```suggestion
  - 管理者に関しても募集中です！Svelte日本Discordで[`#svelteクイズ`](https://discord.com/channels/777141291800723468/844153920241664041)または運営スタッフへのDMにてご連絡ください
```
文面を書くのを忘れてました。すみません

2021-05-25 07:59 UTC, knj4484 commented on README.md
> +- 何らかの理由により当日投稿できない、もしくは出題者本人による投稿を望まない場合は、ISSUE にてお知らせください
```suggestion
- 何らかの理由により当日投稿できない、もしくは出題者本人による投稿を望まない場合は、Issueにてお知らせください
```

2021-05-25 08:00 UTC, merged